.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -160,28 +160,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
 
-      - name: Output latest SHA and tag
+      - name: Output latest SHA
         id: output-sha
         run: |
           LATEST_LOCAL_SHA=$(git rev-parse HEAD)
           echo "LATEST_LOCAL_SHA is $LATEST_LOCAL_SHA"
           echo "latest_local_sha=$LATEST_LOCAL_SHA" >> $GITHUB_OUTPUT
-          # Escape for regex e.g. 2.0 => 2\.0
-          ESCAPED_REF_NAME="${GITHUB_REF_NAME/./"\."}"
-          
-          echo "ESCAPED_REF_NAME is $ESCAPED_REF_NAME"
-          echo "== 1 =="
-          git tag
-          echo "== 2 =="
-          git tag | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$
-          echo "== 3 =="
-          git tag | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$ | sort -V -r
-          echo "== 4 =="
           git tag | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$ | sort -V -r | head -n 1
-
-          LATEST_TAG=$(git tag | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$ | sort -V -r | head -n 1)
-          echo "LATEST_TAG is $LATEST_TAG"
-          echo "latest_test=$LATEST_TAG" >> $GITHUB_OUTPUT
 
       # - name: Install PHP
       #   # SHA will need to be updated to support new php version when they are released
@@ -770,13 +755,7 @@ jobs:
             DO_RELEASE=0
           fi
 
-          # Must have detected an existing tag on the minor branch to do a patch release
-          if [[ $LATEST_TAG == "" ]]; then
-            echo "Not patch releasing because cannot find latest tag"
-            DO_RELEASE=0
-          fi
-
-          # Validate that this commit is that latest commit for the branch
+          # Validate that this commit is that latest commit for the branch using GitHub API
           # We need to check this in case re-rerunning an old job and there have been new commits since
           if [[ $DO_RELEASE == "1" ]]; then
             # https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28
@@ -792,7 +771,6 @@ jobs:
               exit 1
             fi
             LATEST_REMOTE_SHA=$(jq -r '.[0].sha' __response.json)
-            rm __response.json
             echo "LATEST_REMOTE_SHA is $LATEST_REMOTE_SHA"
             echo "LATEST_LOCAL_SHA is $LATEST_LOCAL_SHA"
             if [[ $LATEST_REMOTE_SHA != $LATEST_LOCAL_SHA ]]; then
@@ -801,14 +779,42 @@ jobs:
             fi
           fi
 
-          # Check if there is anything relevant to release
+          # Check is there is an existing tag on the branch using GitHub API
+          # Note cannot use local `git tag` because actions/checkout by default will not checkout tags
+          # and you need to checkout full history in order to get them
+          LATEST_TAG=""
+          NEXT_TAG=""
           if [[ $DO_RELEASE == "1" ]]; then
-            [[ $LATEST_TAG =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]
-            MAJOR=${BASH_REMATCH[1]}
-            MINOR=${BASH_REMATCH[2]}
-            PATCH=${BASH_REMATCH[3]}
-            NEXT_TAG="$MAJOR.$MINOR.$((PATCH+1))"
-            echo "NEXT_TAG is $NEXT_TAG"
+            # https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28
+            RESP_CODE=$(curl -w %{http_code} -s -o __response.json \
+            -X GET https://api.github.com/repos/${GITHUB_REPOSITORY}/tags?per_page=100 \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            )
+            if [[ $RESP_CODE != "200" ]]; then
+              echo "Unable to read list of commits - HTTP response code was $RESP_CODE"
+              exit 1
+            fi
+            # Get the latest tag
+            # Escape for regex e.g. 2.0 => 2\.0
+            ESCAPED_REF_NAME="${GITHUB_REF_NAME/./"\."}"
+            LATEST_TAG=$(jq -r '.[].name' __response.json | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$ | sort -V -r | head -n 1)
+            echo "LATEST_TAG is $LATEST_TAG"
+            if ! [[ $LATEST_TAG =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
+              echo "Not patch releasing because cannot find a matching semver tag on the branch"
+              DO_RELEASE=0
+            else
+              MAJOR=${BASH_REMATCH[1]}
+              MINOR=${BASH_REMATCH[2]}
+              PATCH=${BASH_REMATCH[3]}
+              NEXT_TAG="$MAJOR.$MINOR.$((PATCH+1))"
+              echo "NEXT_TAG is $NEXT_TAG"
+            fi
+          fi
+
+          # Check if there is anything relevant to release using GitHub API
+          if [[ $DO_RELEASE == "1" ]]; then
             # Check on github release notes api if there's anything worth releasing
             # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release
             RESP_CODE=$(curl -w %{http_code} -s -o __response.json \
@@ -827,14 +833,10 @@ jobs:
             )
             if [[ $RESP_CODE != "200" ]]; then
               echo "Unable to fetch release notes - HTTP response code was $RESP_CODE"
-              if [[ -f __response.json ]]; then
-                rm __response.json
-              fi
               exit 1
             fi
             cat __response.json
             # TODO: jq to check if there's anything in the "body"
-            rm __response.json
           fi
           echo "do_release output is $DO_RELEASE"
           echo "do_release=$DO_RELEASE" >> $GITHUB_OUTPUT
