NEW Auto patch releases

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,6 +57,7 @@ jobs:
       GITHUB_REF: ${{ github.ref }}
       GITHUB_REF_NAME: ${{ github.ref_name }}
       GITHUB_REPOSITORY: ${{ github.repository }}
+      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
       GITHUB_EVENT_NAME: ${{ github.event_name }}
     steps:
       - name: Context
@@ -74,6 +75,8 @@ jobs:
           # gitbub.repository - The owner and repository name. For example, Codertocat/Hello-World
           # On forked repos, this will show <account_of_fork>/<repo>
           echo "github.repository: $GITHUB_REPOSITORY"
+          # The repository owner's username. For example, octocat
+          echo "github.repository_owner: $GITHUB_REPOSITORY_OWNER"
           # github.event_name - The event that triggered the workflow
           echo "github.event_name: $GITHUB_EVENT_NAME"
 
@@ -147,6 +150,9 @@ jobs:
       artifacts_name: ${{ matrix.name }}
 
     name: ${{ matrix.name }}
+
+    outputs:
+      latest_local_sha: ${{ steps.output-sha.outputs.latest_local_sha }}
 
     steps:
 
@@ -680,6 +686,13 @@ jobs:
           endtoend_config: ${{ matrix.endtoend_config }}
           js: ${{ matrix.js }}
 
+      - name: Output latest SHA
+        id: output-sha
+        run: |
+          LATEST_LOCAL_SHA=$(git rev-parse HEAD)
+          echo "LATEST_LOCAL_SHA is $LATEST_LOCAL_SHA"
+          echo "latest_local_sha=$LATEST_LOCAL_SHA" >> $GITHUB_OUTPUT
+
       - name: Copy artifacts
         if: always()
         env:
@@ -712,3 +725,164 @@ jobs:
         with:
           name: ${{ env.artifacts_name }}
           path: artifacts
+
+  gaugerelease:
+    name: Check unreleased changes
+    runs-on: ubuntu-latest
+    needs: tests
+    # TODO: restricted to silverstripe/silverstripe-framework - remove once we've validated this whole thing works
+    if: ${{ github.repository == 'silverstripe/silverstripe-framework' && github.repository_owner == 'silverstripe' && (github.event_name == 'push' ||  github.event_name == 'schedule') }}
+    env:
+      GITHUB_REPOSITORY: ${{ github.repository }}
+      GITHUB_REF_NAME: ${{ github.ref_name }}
+      GITHUB_SHA: ${{ github.sha }}
+      LATEST_LOCAL_SHA: ${{ needs.tests.outputs.latest_local_sha }}
+    outputs:
+      do_release: ${{ steps.determine-if.outputs.do_release }}
+      next_tag: ${{ steps.determine-if.outputs.next_tag }}
+    steps:
+
+      - name: Determine if should patch release
+        id: determine-if
+        run: |
+          DO_RELEASE=1
+
+          # Must be on a minor branch to do a patch release
+          if ! [[ $GITHUB_REF_NAME =~ ^[0-9]+\.[0.9]+$ ]]; then
+            echo "Not patch releasing because not on a minor branch"
+            DO_RELEASE=0
+          fi
+
+          # Validate that this commit is that latest commit for the branch using GitHub API
+          # We need to check this in case re-rerunning an old job and there have been new commits since
+          if [[ $DO_RELEASE == "1" ]]; then
+            # https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28
+            AMP='&'
+            RESP_CODE=$(curl -w %{http_code} -s -o __response.json \
+            -X GET https://api.github.com/repos/${GITHUB_REPOSITORY}/commits?sha=${GITHUB_REF_NAME}${AMP}per_page=1 \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            )
+            if [[ $RESP_CODE != "200" ]]; then
+              echo "Unable to read list of commits - HTTP response code was $RESP_CODE"
+              exit 1
+            fi
+            LATEST_REMOTE_SHA=$(jq -r '.[0].sha' __response.json)
+            echo "LATEST_REMOTE_SHA is $LATEST_REMOTE_SHA"
+            echo "LATEST_LOCAL_SHA is $LATEST_LOCAL_SHA"
+            if [[ $LATEST_REMOTE_SHA != $LATEST_LOCAL_SHA ]]; then
+              echo "Not patch releasing because latest remote sha is not equal to latest local sha"
+              DO_RELEASE=0
+            fi
+            # Also validate the sha matches GITHUB_SHA, which is what gha-tag-release will use
+            if [[ $GITHUB_SHA != $LATEST_LOCAL_SHA ]]; then
+              echo "Not patch releasing because GITHUB_SHA is not equal to latest local sha"
+              DO_RELEASE=0
+            fi
+          fi
+
+          # Check is there is an existing tag on the branch using GitHub API
+          # Note cannot use local `git tag` because actions/checkout by default will not checkout tags
+          # and you need to checkout full history in order to get them
+          LATEST_TAG=""
+          NEXT_TAG=""
+          if [[ $DO_RELEASE == "1" ]]; then
+            # https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28
+            RESP_CODE=$(curl -w %{http_code} -s -o __response.json \
+            -X GET https://api.github.com/repos/${GITHUB_REPOSITORY}/tags?per_page=100 \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            )
+            if [[ $RESP_CODE != "200" ]]; then
+              echo "Unable to read list of tags - HTTP response code was $RESP_CODE"
+              exit 1
+            fi
+            # Get the latest tag
+            # Escape for regex e.g. 2.0 => 2\.0
+            ESCAPED_REF_NAME="${GITHUB_REF_NAME/./"\."}"
+            LATEST_TAG=$(jq -r '.[].name' __response.json | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$ | sort -V -r | head -n 1)
+            echo "LATEST_TAG is $LATEST_TAG"
+            echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
+            if ! [[ $LATEST_TAG =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
+              echo "Not patch releasing because cannot find a matching semver tag on the branch"
+              DO_RELEASE=0
+            else
+              MAJOR=${BASH_REMATCH[1]}
+              MINOR=${BASH_REMATCH[2]}
+              PATCH=${BASH_REMATCH[3]}
+              NEXT_TAG="$MAJOR.$MINOR.$((PATCH+1))"
+              echo "NEXT_TAG is $NEXT_TAG"
+              echo "next_tag=$NEXT_TAG" >> $GITHUB_OUTPUT
+            fi
+          fi
+
+          # Check if there is anything relevant to release using GitHub API
+          # The API results include all merged pull-requests, not commits
+          # Pull-requests prefixed with MNT or DOC will not be considered relevant for releasing
+          if [[ $DO_RELEASE == "1" ]]; then
+            # Check on github release notes api if there's anything worth releasing
+            # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release
+            RESP_CODE=$(curl -w %{http_code} -s -o __response.json \
+            -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/releases/generate-notes \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d @- << EOF
+            {
+              "tag_name": "$NEXT_TAG",
+              "target_commitish": "$LATEST_LOCAL_SHA",
+              "previous_tag_name": "$LATEST_TAG"
+            }
+          EOF
+            # ^ The EOF line above intentionally indented like it is
+            )
+            if [[ $RESP_CODE != "200" ]]; then
+              echo "Unable to fetch release notes - HTTP response code was $RESP_CODE"
+              cat __response.json
+              exit 1
+            fi
+            # Get raw body for text parsing
+            jq -r '.body' __response.json > __body.json
+            # Parse release notes one line at a time
+            IS_PRS_SECTION=0
+            HAS_THINGS_TO_RELEASE=0
+            while IFS="" read -r line || [[ -n $line ]]; do
+              echo "$line"
+              if [[ $IS_PRS_SECTION == "0" ]]; then
+                if [[ "$line" == "## What's Changed" ]]; then
+                  IS_PRS_SECTION=1
+                fi
+              else
+                if [[ "$line" =~ ^\*[[:space:]](.+?)$ ]]; then
+                  PR_TITLE=${BASH_REMATCH[1]}
+                  if ! [[ $PR_TITLE =~ ^(MNT|DOC) ]]; then
+                    HAS_THINGS_TO_RELEASE=1
+                  fi
+                else
+                  IS_PRS_SECTION=0
+                fi
+              fi
+            done < __body.json
+            if [[ $HAS_THINGS_TO_RELEASE == "0" ]]; then
+              echo "Not patch releasing because there is nothing relevant to release"
+              DO_RELEASE=0
+            fi
+          fi
+          echo "do_release output is $DO_RELEASE"
+          echo "do_release=$DO_RELEASE" >> $GITHUB_OUTPUT
+
+  patchrelease:
+    name: Patch release
+    runs-on: ubuntu-latest
+    needs: gaugerelease
+    if: ${{ needs.gaugerelease.outputs.do_release == '1' }}
+    steps:
+      - name: Patch release
+        uses: silverstripe/gha-tag-release@v1
+        with:
+          tag: ${{ needs.gaugerelease.outputs.next_tag }}
+          delete_existing: false
+          release: true
+          release_auto_notes: true
