.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -148,6 +148,7 @@ jobs:
 
     env:
       artifacts_name: ${{ matrix.name }}
+      GITHUB_REF_NAME: ${{ github.ref_name }}
 
     name: ${{ matrix.name }}
 
@@ -159,12 +160,17 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
 
-      - name: Output latest SHA
+      - name: Output latest SHA and tag
         id: output-sha
         run: |
           LATEST_LOCAL_SHA=$(git rev-parse HEAD)
           echo "LATEST_LOCAL_SHA is $LATEST_LOCAL_SHA"
           echo "latest_local_sha=$LATEST_LOCAL_SHA" >> $GITHUB_OUTPUT
+          # Escape for regex e.g. 2.0 => 2\.0
+          ESCAPED_REF_NAME="${GITHUB_REF_NAME/./"\."}"
+          LATEST_TAG=$(git tag | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$ | sort -V -r | head -n 1)
+          echo "LATEST_TAG is $LATEST_TAG"
+          echo "latest_test=$LATEST_TAG" >> $GITHUB_OUTPUT
 
       # - name: Install PHP
       #   # SHA will need to be updated to support new php version when they are released
@@ -737,6 +743,7 @@ jobs:
       GITHUB_REPOSITORY: ${{ github.repository }}
       GITHUB_REF_NAME: ${{ github.ref_name }}
       LATEST_LOCAL_SHA: ${{ needs.tests.outputs.latest_local_sha }}
+      LATEST_TAG: ${{ needs.tests.outputs.latest_tag }}
     outputs:
       do_release: ${{ steps.determine-if.outputs.do_release }}
     steps:
@@ -749,6 +756,12 @@ jobs:
           # Must be on a minor branch to do a patch release
           if ! [[ $GITHUB_REF_NAME =~ ^[0-9]+\.[0.9]+$ ]]; then
             echo "Not patch releasing because not on a minor branch"
+            DO_RELEASE=0
+          fi
+
+          # Must have detected an existing tag on the minor branch to do a patch release
+          if [[ $LATEST_TAG == "" ]]; then
+            echo "Not patch releasing because cannot find latest tag"
             DO_RELEASE=0
           fi
 
@@ -779,47 +792,38 @@ jobs:
 
           # Check if there is anything relevant to release
           if [[ $DO_RELEASE == "1" ]]; then
-            # Escape for regex e.g. 2.0 => 2\.0
-            ESCAPED_REF_NAME="${GITHUB_REF_NAME/./"\."}"
-            LATEST_TAG=$(git tag | grep -E ^$ESCAPED_REF_NAME\.[0-9]+$ | sort -V -r | head -n 1)
-            echo "LATEST_TAG is $LATEST_TAG"
-            if [[ $LATEST_TAG == "" ]]; then
-              echo "Not patch releasing because cannot find latest tag"
-              DO_RELEASE=0
-            else
-              [[ $LATEST_TAG =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]
-              MAJOR=${BASH_REMATCH[1]}
-              MINOR=${BASH_REMATCH[2]}
-              PATCH=${BASH_REMATCH[3]}
-              NEXT_TAG="$MAJOR.$MINOR.$((PATCH+1))"
-              echo "NEXT_TAG is $NEXT_TAG"
-              # Check on github release notes api if there's anything worth releasing
-              # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release
-              RESP_CODE=$(curl -w %{http_code} -s -o __response.json \
-              -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/releases/generate-notes \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ github.token }}" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              -d @- << EOF
-              {
-                "tag_name": "$NEXT_TAG",
-                "target_commitish": "$LATEST_LOCAL_SHA",
-                "previous_tag_name": "$LATEST_TAG"
-              }
-              # The following line with EOF in it is intentionally indented like it is
+            [[ $LATEST_TAG =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]
+            MAJOR=${BASH_REMATCH[1]}
+            MINOR=${BASH_REMATCH[2]}
+            PATCH=${BASH_REMATCH[3]}
+            NEXT_TAG="$MAJOR.$MINOR.$((PATCH+1))"
+            echo "NEXT_TAG is $NEXT_TAG"
+            # Check on github release notes api if there's anything worth releasing
+            # https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release
+            RESP_CODE=$(curl -w %{http_code} -s -o __response.json \
+            -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/releases/generate-notes \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            -d @- << EOF
+            {
+              "tag_name": "$NEXT_TAG",
+              "target_commitish": "$LATEST_LOCAL_SHA",
+              "previous_tag_name": "$LATEST_TAG"
+            }
+            # The following line with EOF in it is intentionally indented like it is
           EOF
-              )
-              if [[ $RESP_CODE != "200" ]]; then
-                echo "Unable to fetch release notes - HTTP response code was $RESP_CODE"
-                if [[ -f __response.json ]]; then
-                  rm __response.json
-                fi
-                exit 1
+            )
+            if [[ $RESP_CODE != "200" ]]; then
+              echo "Unable to fetch release notes - HTTP response code was $RESP_CODE"
+              if [[ -f __response.json ]]; then
+                rm __response.json
               fi
-              cat __response.json
-              # TODO: jq to check if there's anything in the "body"
-              rm __response.json
+              exit 1
             fi
+            cat __response.json
+            # TODO: jq to check if there's anything in the "body"
+            rm __response.json
           fi
           echo "do_release output is $DO_RELEASE"
           echo "do_release=$DO_RELEASE" >> $GITHUB_OUTPUT
